Repository ENOT-AutoDL/onnx2torch, pull requests merged in 2022-07, with the labels that each got.

#71 Add PReLU opr
  onnx2torch/node_converters/activations.py
  tests/node_converters/activations_test.py
Labels: feat

#74 FIX: torch 1.12 errors
  onnx2torch/node_converters/clip.py
  onnx2torch/node_converters/roialign.py
  onnx2torch/utils/common.py
  tests/node_converters/slice_test.py
  tests/utils/common.py
Labels: bug

#80 fixed prelu according specs
  onnx2torch/node_converters/activations.py
  tests/node_converters/activations_test.py
Labels: bug

#81 fixed export to onnx (global avg pool)
  onnx2torch/node_converters/global_average_pool.py
  tests/node_converters/global_avg_pool_test.py
Labels: refactoring
