Repository ENOT-AutoDL/onnx2torch, pull requests merged in 2022-01, with the labels that each got.

#9 Pow
  onnx2torch/common.py
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/binary_math_operations.py
  onnx2torch/node_converters/pow.py
  tests/node_converters/pow_test.py
Labels: enhancement

#8 New activations
  onnx2torch/node_converters/activations.py
  tests/node_converters/activations_test.py
Labels: enhancement

#10 Optional args
  onnx2torch/converter.py
  onnx2torch/node_converters/nms.py
  onnx2torch/onnx_graph.py
  tests/node_converters/nms_test.py
Labels: bug, enhancement

#13 FIX: squeeze/unsqueeze/nms operations
  onnx2torch/converter.py
  onnx2torch/custom_export_to_onnx.py
  onnx2torch/node_converters/expand.py
  onnx2torch/node_converters/nms.py
  onnx2torch/node_converters/scatter_nd.py
  onnx2torch/node_converters/squeeze.py
  onnx2torch/node_converters/unsqueeze.py
  tests/node_converters/nms_test.py
  tests/node_converters/squeeze_test.py
  tests/node_converters/unsqueeze_test.py
Labels: bug

#14 add logical operations
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/logical.py
  tests/node_converters/binary_operations_test.py
  tests/node_converters/logical_test.py
Labels: enhancement

#12 Reduce
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/reduce.py
  onnx2torch/node_converters/reduce_max.py
  tests/node_converters/reduce_max_test.py
  tests/node_converters/reduce_test.py
Labels: enhancement

#15 Resize
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/resize.py
  tests/node_converters/resize_test.py
Labels: enhancement

#20 FIX: resize inputs
  onnx2torch/node_converters/resize.py
Labels: bug

#19 Fix: average pool
  onnx2torch/common.py
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/average_pool.py
  onnx2torch/node_converters/conv.py
  onnx2torch/node_converters/max_pool.py
  tests/node_converters/average_pool_max_pool_test.py
  tests/node_converters/max_pool_test.py
Labels: bug
