Repository ENOT-AutoDL/onnx2torch, pull requests merged in 2022-09, with the labels that each got.

#97 Add Dropout
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/dropout.py
  operators.md
  tests/node_converters/dropout_test.py
Labels: feat

#104 FIX: gemm operation updated according onnx specs
  onnx2torch/node_converters/gemm.py
  tests/node_converters/gemm_test.py
Labels: fix

#105 chore: remove format wheel badge from README
  README.md
Labels: documentation
