Repository ENOT-AutoDL/onnx2torch, pull requests merged in 2022-08, with the labels that each got.

#84 FIX: fixed shape inference of big models
  onnx2torch/utils/safe_shape_inference.py
Labels: bug

#86 FIX: updated batch norm converter according onnx specs
  onnx2torch/node_converters/average_pool.py
  onnx2torch/node_converters/batch_norm.py
  onnx2torch/node_converters/conv.py
  onnx2torch/node_converters/max_pool.py
  onnx2torch/node_converters/pad.py
  tests/node_converters/batch_norm_test.py
  tests/utils/common.py
Labels: bug

#89 fix(ci): isort not working
  .github/workflows/lint.yml
Labels: fix

#88 Fix type annotation
  onnx2torch/utils/safe_shape_inference.py
Labels: fix

#90 FEATURE: added asymmetric padding for Conv and MaxPool
  onnx2torch/node_converters/average_pool.py
  onnx2torch/node_converters/binary_math_operations.py
  onnx2torch/node_converters/conv.py
  onnx2torch/node_converters/max_pool.py
  onnx2torch/node_converters/pad.py
  onnx2torch/utils/common.py
  onnx2torch/utils/padding.py
  tests/node_converters/average_pool_max_pool_test.py
  tests/node_converters/conv_test.py
  tests/node_converters/pad_test.py
Labels: enhancement
