Repository ENOT-AutoDL/onnx2torch, pull requests merged in 2023-02, with the labels that each got.

#127 refactor: simplify custom export to ONNX
  .pre-commit-config.yaml
  README.md
  onnx2torch/node_converters/activations.py
  onnx2torch/node_converters/base_element_wise.py
  onnx2torch/node_converters/conv.py
  onnx2torch/node_converters/cumsum.py
  onnx2torch/node_converters/dropout.py
  onnx2torch/node_converters/expand.py
  onnx2torch/node_converters/gather.py
  onnx2torch/node_converters/global_average_pool.py
  onnx2torch/node_converters/logical.py
  onnx2torch/node_converters/mean.py
  onnx2torch/node_converters/min_max.py
  onnx2torch/node_converters/nms.py
  onnx2torch/node_converters/pad.py
  onnx2torch/node_converters/reduce.py
  onnx2torch/node_converters/reshape.py
  onnx2torch/node_converters/roialign.py
  onnx2torch/node_converters/scatter_nd.py
  onnx2torch/node_converters/shape.py
  onnx2torch/node_converters/slice.py
  onnx2torch/node_converters/squeeze.py
  onnx2torch/node_converters/sum.py
  onnx2torch/node_converters/tile.py
  onnx2torch/node_converters/unsqueeze.py
  onnx2torch/utils/custom_export_to_onnx.py
  tests/node_converters/flatten_test.py
  tests/node_converters/gather_test.py
  tests/node_converters/gemm_test.py
  tests/node_converters/nms_test.py
  tests/node_converters/pad_test.py
  tests/node_converters/range_test.py
  tests/node_converters/reduce_test.py
  tests/node_converters/resize_test.py
Labels: refactoring

#130 docs: workaround for old opset versions
  README.md
Labels: documentation

#131 feat: InstanceNormalization
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/instance_norm.py
  operators.md
  tests/node_converters/instance_norm_test.py
Labels: feat

#139 feat: Mod
  onnx2torch/node_converters/__init__.py
  onnx2torch/node_converters/mod.py
  operators.md
  tests/node_converters/mod_test.py
Labels: feat
